# Generated by Django 5.2.7 on 2025-10-08 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingVector',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('product', 'product'), ('faq', 'faq')], max_length=20)),
                ('source_obj_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('vector', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FAQChunk',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('accords', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('longevity', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('popularity', models.FloatField(default=0.0)),
            ],
        ),
    ]
